### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by ping0xFF** [DynamoMTL/spree_smart_free_shipping#1]
I created a promotion, added a rule for any orders > $15, then added an action of "Make Shipping Method(s) Free", then I added the codes for my shipping methods, but it's not making it free. Am I missing a step?

[Here](https://github.com/spree/spree/issues/6745), dangerdogz mentions that after you set the codes, you use a custom calculator to set the shipping cost to 0, but I am not seeing it.

**Comment by ping0xFF** [comment]
Okay, I figured it out. In addition to the "Make Shipping Method(s) Free" action, I had to add the "Free Shipping" rule as well.

Thanks for the gem, it's just what I needed.

**Comment by ping0xFF** [comment]
I take that back. Adding the "Free Shipping" rule as well, didn't help..

**Comment by braidn** [comment]
@sybind what version of Spree/Solidus are you rocking?

**Comment by ping0xFF** [comment]
Using Spree 2.4

**Comment by sybind** [comment]
I kinda have an idea what's going on. It seems it can't find the calculator method for the free shipping action. 

```
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)> package.order.promotions.any? do |p|    
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)*   p.eligible?(package.order) &&      
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)*   p.promotion_actions.any? do |action|      
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)*     action.calculator.selected_shipping_methods.include?(calculable)
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)*   end        
[37] pry(#<Spree::Calculator::Shipping::FlatRate>)* end      
  CACHE (0.0ms)  SELECT COUNT(*) FROM "spree_line_items" INNER JOIN "spree_variants" ON "spree_variants"."id" = "spree_line_items"."variant_id" AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_products" ON "spree_products"."id" = "spree_variants"."product_id" AND "spree_products"."deleted_at" IS NULL WHERE "spree_line_items"."order_id" = ? AND "spree_products"."promotionable" = 't'  [["order_id", 19]]
  CACHE (0.0ms)  SELECT "spree_shipping_methods".* FROM "spree_shipping_methods"  WHERE "spree_shipping_methods"."deleted_at" IS NULL AND "spree_shipping_methods"."admin_name" IN ('801')
NoMethodError: undefined method `calculator' for #<Spree::Promotion::Actions::FreeShipping:0x0000000b5b1ef8>
from /usr/local/rvm/gems/ruby-2.2.1@mystore20151008/gems/activemodel-4.1.11/lib/active_model/attribute_methods.rb:435:in `method_missing'
```

**Comment by ping0xFF** [comment]
I got it to work! Nothing is wrong with the code. My problem was that I put the shipping method codes in the incorrect field of my shipping method. I assumed putting the codes in the "Code" field of my shipping method was correct. The correct place to put them is in the "Internal Name" field of the shipping method.

**Comment by braidn** [comment]
@sybind glad to hear you got it working! Thank you very much for closing the issue.
